using System;
using System.Collections.Generic;
using System.Text;

namespace Remove_Top.Features.Normalization
{
    /// <summary>
    /// Corrector ortográfico local para nombres de canciones en español.
    /// Aplica tildes a palabras conocidas preservando la capitalización original
    /// de cada palabra. Operación idempotente: si el nombre ya está bien, lo
    /// devuelve sin cambios.
    /// </summary>
    public static class SpanishNameCorrector
    {
        /// <summary>
        /// Diccionario de palabras sin tilde (lowercase) → palabra con tilde (lowercase).
        /// Solo incluye palabras que en títulos de canciones casi siempre llevan tilde.
        /// Palabras ambiguas (mas, si, tu) se incluyen porque en contextos musicales
        /// predomina la forma acentuada.
        /// </summary>
        private static readonly Dictionary<string, string> AccentedWords = new(StringComparer.OrdinalIgnoreCase)
        {
            // --- Monosílabos acentuados ---
            ["mas"] = "más",
            ["si"] = "sí",
            ["tu"] = "tú",
            ["el"] = "él",
            ["mi"] = "mí",
            ["te"] = "té",
            ["se"] = "sé",
            ["de"] = "de",
            ["aun"] = "aún",
            ["ay"] = "ay",
            ["ea"] = "ea",

            // --- Adverbios y pronombres interrogativos/exclamativos ---
            ["asi"] = "así",
            ["aqui"] = "aquí",
            ["ahi"] = "ahí",
            ["alla"] = "allá",
            ["cuando"] = "cuándo",
            ["como"] = "cómo",
            ["que"] = "qué",
            ["quien"] = "quién",
            ["donde"] = "dónde",
            ["cuanto"] = "cuánto",
            ["cual"] = "cuál",
            ["cuales"] = "cuáles",
            ["cuantos"] = "cuántos",
            ["cuantas"] = "cuántas",
            ["quantos"] = "cuántos",
            ["quantas"] = "cuántas",
            ["quanto"] = "cuánto",
            ["quanta"] = "cuánta",

            // --- Sustantivos comunes ---
            ["corazon"] = "corazón",
            ["corazones"] = "corazones",
            ["cancion"] = "canción",
            ["canciones"] = "canciones",
            ["musica"] = "música",
            ["musico"] = "músico",
            ["musicales"] = "musicales",
            ["dia"] = "día",
            ["dias"] = "días",
            ["lagrima"] = "lágrima",
            ["lagrimas"] = "lágrimas",
            ["angel"] = "ángel",
            ["angeles"] = "ángeles",
            ["pagina"] = "página",
            ["paginas"] = "páginas",
            ["arbol"] = "árbol",
            ["arboles"] = "árboles",
            ["lapiz"] = "lápiz",
            ["cáliz"] = "cáliz",
            ["palabra"] = "palabra",
            ["palabras"] = "palabras",
            ["mano"] = "mano",
            ["manos"] = "manos",
            ["amor"] = "amor",
            ["amores"] = "amores",
            ["soledad"] = "soledad",
            ["felicidad"] = "felicidad",
            ["verdad"] = "verdad",
            ["razon"] = "razón",
            ["razones"] = "razones",
            ["ilusion"] = "ilusión",
            ["ilusiones"] = "ilusiones",
            ["pasion"] = "pasión",
            ["pasiones"] = "pasiones",
            ["mision"] = "misión",
            ["misiones"] = "misiones",
            ["decision"] = "decisión",
            ["decisiones"] = "decisiones",
            ["religion"] = "religión",
            ["atencion"] = "atención",
            ["direccion"] = "dirección",
            ["direcciones"] = "direcciones",
            ["condicion"] = "condición",
            ["condiciones"] = "condiciones",
            ["tradicion"] = "tradición",
            ["tradiciones"] = "tradiciones",
            ["emocion"] = "emoción",
            ["emociones"] = "emociones",
            ["explosion"] = "explosión",
            ["inspiracion"] = "inspiración",
            ["educacion"] = "educación",
            ["situacion"] = "situación",
            ["informacion"] = "información",
            ["aplicacion"] = "aplicación",
            ["imitacion"] = "imitación",
            ["admiracion"] = "admiración",
            ["nacion"] = "nación",
            ["naciones"] = "naciones",
            ["casion"] = "ocasión",
            ["ocasiones"] = "ocasiones",
            ["oracion"] = "oración",
            ["oraciones"] = "oraciones",
            ["relacion"] = "relación",
            ["relaciones"] = "relaciones",
            ["posicion"] = "posición",
            ["posiciones"] = "posiciones",
            ["icion"] = "ición",
            ["mision"] = "misión",
            ["vision"] = "visión",
            ["version"] = "versión",
            ["versiones"] = "versiones",
            ["pregunta"] = "pregunta",
            ["preguntas"] = "preguntas",
            ["respuesta"] = "respuesta",
            ["respuestas"] = "respuestas",
            ["noche"] = "noche",
            ["noches"] = "noches",
            ["sol"] = "sol",
            ["luna"] = "luna",
            ["lunas"] = "lunas",
            ["mar"] = "mar",
            ["cielo"] = "cielo",
            ["cielos"] = "cielos",
            ["fuego"] = "fuego",
            ["agua"] = "agua",
            ["tierra"] = "tierra",
            ["tierras"] = "tierras",
            ["viento"] = "viento",
            ["vientos"] = "vientos",
            ["lluvia"] = "lluvia",
            ["lluvias"] = "lluvias",
            ["frio"] = "frío",
            ["calor"] = "calor",
            ["sombra"] = "sombra",
            ["sombras"] = "sombras",
            ["luz"] = "luz",
            ["luces"] = "luces",
            ["paz"] = "paz",
            ["guerra"] = "guerra",
            ["guerras"] = "guerras",
            ["dolor"] = "dolor",
            ["dolores"] = "dolores",
            ["alma"] = "alma",
            ["almas"] = "almas",
            ["cuerpo"] = "cuerpo",
            ["cuerpos"] = "cuerpos",
            ["sueno"] = "sueño",
            ["suenos"] = "sueños",
            ["camino"] = "camino",
            ["caminos"] = "caminos",
            ["vida"] = "vida",
            ["vidas"] = "vidas",
            ["muerte"] = "muerte",
            ["muertes"] = "muertes",
            ["amigo"] = "amigo",
            ["amigos"] = "amigos",
            ["amiga"] = "amiga",
            ["amigas"] = "amigas",
            ["hermano"] = "hermano",
            ["hermanos"] = "hermanos",
            ["hermana"] = "hermana",
            ["hermanas"] = "hermanas",
            ["padre"] = "padre",
            ["madre"] = "madre",
            ["hijo"] = "hijo",
            ["hija"] = "hija",
            ["hijos"] = "hijos",
            ["hijas"] = "hijas",
            ["familia"] = "familia",
            ["esposo"] = "esposo",
            ["esposa"] = "esposa",
            ["bebe"] = "bebé",
            ["nina"] = "niña",
            ["nino"] = "niño",
            ["ninos"] = "niños",
            ["ninas"] = "niñas",
            ["chico"] = "chico",
            ["chica"] = "chica",
            ["chicos"] = "chicos",
            ["chicas"] = "chicas",
            ["joven"] = "joven",
            ["jovenes"] = "jóvenes",
            ["viejo"] = "viejo",
            ["vieja"] = "vieja",
            ["bonito"] = "bonito",
            ["bonita"] = "bonita",
            ["lindo"] = "lindo",
            ["linda"] = "linda",
            ["feo"] = "feo",
            ["fea"] = "fea",
            ["bueno"] = "bueno",
            ["buena"] = "buena",
            ["malo"] = "malo",
            ["mala"] = "mala",
            ["grande"] = "grande",
            ["pequeño"] = "pequeño",
            ["pequeña"] = "pequeña",
            ["nuevo"] = "nuevo",
            ["nueva"] = "nueva",
            ["viejo2"] = "viejo",
            ["vieja2"] = "vieja",
            ["feliz"] = "feliz",
            ["triste"] = "triste",
            ["alegre"] = "alegre",
            ["contento"] = "contento",
            ["contenta"] = "contenta",
            ["enamorado"] = "enamorado",
            ["enamorada"] = "enamorada",
            ["loco"] = "loco",
            ["loca"] = "loca",
            ["solo"] = "solo",
            ["sola"] = "sola",
            ["siempre"] = "siempre",
            ["nunca"] = "nunca",
            ["tarde"] = "tarde",
            ["temprano"] = "temprano",
            ["hoy"] = "hoy",
            ["ayer"] = "ayer",
            ["manana"] = "mañana",
            ["anoche"] = "anoche",
            ["pronto"] = "pronto",
            ["despues"] = "después",
            ["antes"] = "antes",
            ["lejos"] = "lejos",
            ["cerca"] = "cerca",
            ["dentro"] = "dentro",
            ["fuera"] = "fuera",
            ["arriba"] = "arriba",
            ["abajo"] = "abajo",

            // --- Verbos pretérito acentuados (muy comunes en canciones) ---
            ["amo"] = "amó",
            ["canto"] = "cantó",
            ["cante"] = "canté",
            ["bailo"] = "bailó",
            ["baila"] = "baila",
            ["vivo"] = "vivió",
            ["vive"] = "vive",
            ["soño"] = "soñó",
            ["sueño"] = "sueño",
            ["llore"] = "lloré",
            ["lloro"] = "lloró",
            ["beso"] = "beso",
            ["beso2"] = "besó",
            ["vio"] = "vio",
            ["dijo"] = "dijo",
            ["hizo"] = "hizo",
            ["puso"] = "puso",
            ["estuvo"] = "estuvo",
            ["partio"] = "partió",
            ["salió"] = "salió",
            ["salio"] = "salió",
            ["corrio"] = "corrió",
            ["murio"] = "murió",
            ["nacio"] = "nació",
            ["sintio"] = "sintió",
            ["durmirio"] = "durmió",
            ["durmio"] = "durmió",
            ["comio"] = "comió",
            ["bibio"] = "bebió",
            ["bebio"] = "bebió",
            ["rio"] = "rió",
            ["siguio"] = "siguió",
            ["llego"] = "llegó",
            ["gano"] = "ganó",
            ["perdio"] = "perdió",
            ["abrio"] = "abrió",
            ["cerro"] = "cerró",
            ["cayo"] = "cayó",
            ["creyo"] = "creyó",
            ["leyo"] = "leyó",
            ["oyo"] = "oyó",
            ["construyo"] = "construyó",
            ["destruyo"] = "destruyó",
            ["produjo"] = "produjo",
            ["condujo"] = "condujo",
            ["tradujo"] = "tradujo",
            ["aparecio"] = "apareció",
            ["desaparecio"] = "desapareció",
            ["regreso"] = "regresó",
            ["empezo"] = "empezó",
            ["comenzo"] = "comenzó",
            ["termino"] = "terminó",
            ["rompio"] = "rompió",
            ["rompe"] = "rompe",
            ["sintio"] = "sintió",
            ["sentio"] = "sintió",
            ["penso"] = "pensó",
            ["creo"] = "creó",
            ["busco"] = "buscó",
            ["encontro"] = "encontró",
            ["perdio"] = "perdió",
            ["perder"] = "perder",
            ["encontrar"] = "encontrar",
            ["olvido"] = "olvidó",
            ["olvide"] = "olvidé",
            ["espero"] = "esperó",
            ["espere"] = "esperé",
            ["cambia"] = "cambia",
            ["cambie"] = "cambié",
            ["cambio"] = "cambió",
            ["muero"] = "muero",
            ["muere"] = "muere",
            ["muera"] = "muera",
            ["vuelvo"] = "vuelvo",
            ["vuelve"] = "vuelve",
            ["vuelva"] = "vuelva",
            ["sigo"] = "sigo",
            ["sigue"] = "sigue",
            ["siga"] = "siga",
            ["busco"] = "busco",
            ["busca"] = "busca",
            ["busque"] = "busque",
            ["puedo"] = "puedo",
            ["puede"] = "puede",
            ["pueda"] = "pueda",
            ["quiero"] = "quiero",
            ["quiere"] = "quiere",
            ["quiera"] = "quiera",
            ["necesito"] = "necesito",
            ["necesita"] = "necesita",
            ["necesite"] = "necesite",
            ["tengo"] = "tengo",
            ["tiene"] = "tiene",
            ["tenga"] = "tenga",
            ["doy"] = "doy",
            ["da"] = "da",
            ["dé"] = "dé",
            ["voy"] = "voy",
            ["va"] = "va",
            ["vaya"] = "vaya",
            ["vengas"] = "vengas",
            ["venga"] = "venga",
            ["vengo"] = "vengo",
            ["digo"] = "digo",
            ["dices"] = "dices",
            ["diga"] = "diga",
            ["pongo"] = "pongo",
            ["pone"] = "pone",
            ["ponga"] = "ponga",
            ["salgo"] = "salgo",
            ["sales"] = "sales",
            ["salga"] = "salga",
            ["ando"] = "ando",
            ["ando2"] = "ando",
            ["corre"] = "corre",
            ["corres"] = "corres",
            ["corra"] = "corra",
            ["ando3"] = "ando",
            ["muevo"] = "muevo",
            ["mueves"] = "mueves",
            ["mueva"] = "mueva",

            // --- Números acentuados ---
            ["dieciseis"] = "dieciséis",
            ["veintidos"] = "veintidós",
            ["veintitres"] = "veintitrés",
            ["veintiseis"] = "veintiséis",
            ["veintisiete"] = "veintisiete",
            ["veintiocho"] = "veintiocho",
            ["veintinueve"] = "veintinueve",
            ["treinta"] = "treinta",
            ["cuarenta"] = "cuarenta",
            ["cincuenta"] = "cincuenta",
            ["sesenta"] = "sesenta",
            ["setenta"] = "setenta",
            ["ochenta"] = "ochenta",
            ["noventa"] = "noventa",
            ["ciento"] = "ciento",
            ["mil"] = "mil",

            // --- Días y meses (los que llevan tilde) ---
            ["sabado"] = "sábado",
            ["sabados"] = "sábados",
            ["miercoles"] = "miércoles",
            ["viernes"] = "viernes",
            ["domingo"] = "domingo",
            ["domingos"] = "domingos",
            ["enero"] = "enero",
            ["febrero"] = "febrero",
            ["marzo"] = "marzo",
            ["abril"] = "abril",
            ["mayo"] = "mayo",
            ["junio"] = "junio",
            ["julio"] = "julio",
            ["agosto"] = "agosto",
            ["septiembre"] = "septiembre",
            ["octubre"] = "octubre",
            ["noviembre"] = "noviembre",
            ["diciembre"] = "diciembre",

            // --- Nombres propios comunes en canciones ---
            ["maria"] = "María",
            ["jose"] = "José",
            ["jesus"] = "Jesús",
            ["raul"] = "Raúl",
            ["angel2"] = "Ángel",
            ["daniel"] = "Daniel",
            ["fernando"] = "Fernando",
            ["antonio"] = "Antonio",
            ["francisco"] = "Francisco",
            ["eduardo"] = "Eduardo",
            ["adrian"] = "Adrián",
            ["ruben"] = "Rubén",
            ["julian"] = "Julián",
            ["natalia"] = "Natalia",
            ["cristina"] = "Cristina",
            ["patricia"] = "Patricia",
            ["veronica"] = "Verónica",
            ["monica"] = "Mónica",
            ["claudia"] = "Claudia",
            ["andrea"] = "Andrea",
            ["lucia"] = "Lucía",
            ["africa"] = "África",
            ["america"] = "América",
            ["argentina"] = "Argentina",
            ["colombia"] = "Colombia",
            ["mexico"] = "México",
            ["espana"] = "España",
            ["peru"] = "Perú",
            ["venezuela"] = "Venezuela",
            ["bolivia"] = "Bolivia",
            ["chile"] = "Chile",
            ["brasil"] = "Brasil",
            ["uruguay"] = "Uruguay",
            ["ecuador"] = "Ecuador",
            ["paraguay"] = "Paraguay",

            // --- Títulos de canciones conocidos (variantes comunes) ---
            ["no me queda mas"] = "No Me Queda Más",
            ["la bamba"] = "La Bamba",
            ["despacito"] = "Despacito",
            ["bailando"] = "Bailando",
            ["corazoncito"] = "Corazóncito",
            ["cielito lindo"] = "Cielito Lindo",
            ["guantanamera"] = "Guantanamera",
            ["macarena"] = "Macarena",
            ["livin la vida loca"] = "Livin' La Vida Loca",
            ["maria la del barrio"] = "María La Del Barrio",
            ["la chica de humo"] = "La Chica De Humo",
            ["historia de un amor"] = "Historia De Un Amor",
            ["quizas"] = "Quizás",
            ["tal vez"] = "Tal Vez",
            ["por favor"] = "Por Favor",
            ["te amo"] = "Te Amo",
            ["te quiero"] = "Te Quiero",
            ["mi tierra"] = "Mi Tierra",
            ["el rey"] = "El Rey",
            ["el condor pasa"] = "El Cóndor Pasa",
            ["la leyenda del hada y el mago"] = "La Leyenda Del Hada Y El Mago",

            // --- Palabras musicales ---
            ["acustica"] = "Acústica",
            ["acustico"] = "Acústico",
            ["electrica"] = "Eléctrica",
            ["electrico"] = "Eléctrico",
            ["orquesta"] = "Orquesta",
            ["sinfonia"] = "Sinfonía",
            ["melodia"] = "Melodía",
            ["armonia"] = "Armonía",
            ["ritmo"] = "Ritmo",
            ["tono"] = "Tono",
            ["notas"] = "Notas",
            ["nota"] = "Nota",
            ["tecla"] = "Tecla",
            ["teclas"] = "Teclas",
            ["guitarra"] = "Guitarra",
            ["bateria"] = "Batería",
            ["piano"] = "Piano",
            ["bajo"] = "Bajo",
            ["violin"] = "Violín",
            ["saxofon"] = "Saxofón",
            ["trompeta"] = "Trompeta",
            ["flauta"] = "Flauta",
            ["arpa"] = "Arpa",
            ["bombo"] = "Bombo",
            ["platillo"] = "Platillo",
            ["sonido"] = "Sonido",
            ["sonidos"] = "Sonidos",
            ["grabacion"] = "Grabación",
            ["grabaciones"] = "Grabaciones",
            ["disco"] = "Disco",
            ["discos"] = "Discos",
            ["album"] = "Álbum",
            ["albums"] = "Álbumes",
            ["cinta"] = "Cinta",
            ["radio"] = "Radio",
            ["escenario"] = "Escenario",
            ["palco"] = "Palco",
            ["publico"] = "Público",
            ["concierto"] = "Concierto",
            ["conciertos"] = "Conciertos",
            ["festival"] = "Festival",
            ["fiesta"] = "Fiesta",
            ["fiestas"] = "Fiestas",
            ["baile"] = "Baile",
            ["bailes"] = "Bailes",
            ["canto"] = "Canto",
            ["cantos"] = "Cantos",
            ["vocal"] = "Vocal",
            ["vocalista"] = "Vocalista",
            ["coro"] = "Coro",
            ["coros"] = "Coros",
            ["estrofa"] = "Estrofa",
            ["estrofas"] = "Estrofas",
            ["verso"] = "Verso",
            ["versos"] = "Versos",
            ["rima"] = "Rima",
            ["rimas"] = "Rimas",
            ["letra"] = "Letra",
            ["letras"] = "Letras",
            ["tema"] = "Tema",
            ["temas"] = "Temas",
            ["canciones"] = "Canciones",
            ["pistas"] = "Pistas",
            ["pista"] = "Pista",

            // --- Palabras de amor/desamor comunes en títulos ---
            ["corazon"] = "corazón",
            ["corazones"] = "corazones",
            ["amor"] = "amor",
            ["amores"] = "amores",
            ["desamor"] = "desamor",
            ["desamores"] = "desamores",
            ["beso"] = "beso",
            ["besos"] = "besos",
            ["abrazo"] = "abrazo",
            ["abrazos"] = "abrazos",
            ["carino"] = "cariño",
            ["carinos"] = "cariños",
            ["ternura"] = "ternura",
            ["pasion"] = "pasión",
            ["pasiones"] = "pasiones",
            ["deseo"] = "deseo",
            ["deseos"] = "deseos",
            ["ilusion"] = "ilusión",
            ["ilusiones"] = "ilusiones",
            ["esperanza"] = "esperanza",
            ["esperanzas"] = "esperanzas",
            ["confianza"] = "confianza",
            ["abandono"] = "abandono",
            ["soledad"] = "soledad",
            ["tristeza"] = "tristeza",
            ["pena"] = "pena",
            ["penas"] = "penas",
            ["llanto"] = "llanto",
            ["dolor"] = "dolor",
            ["dolores"] = "dolores",
            ["recuerdo"] = "recuerdo",
            ["recuerdos"] = "recuerdos",
            ["olvido"] = "olvido",
            ["despedida"] = "despedida",
            ["regreso"] = "regreso",
            ["encuentro"] = "encuentro",
            ["encuentros"] = "encuentros",
            ["desencuentro"] = "desencuentro",
            ["desencuentros"] = "desencuentros",
            ["perdon"] = "perdón",
            ["perdones"] = "perdones",
            ["mentira"] = "mentira",
            ["mentiras"] = "mentiras",
            ["verdad"] = "verdad",
            ["verdades"] = "verdades",
            ["secreto"] = "secreto",
            ["secretos"] = "secretos",
            ["destino"] = "destino",
            ["destinos"] = "destinos",
            ["camino"] = "camino",
            ["caminos"] = "caminos",
            ["viaje"] = "viaje",
            ["viajes"] = "viajes",
            ["aventura"] = "aventura",
            ["aventuras"] = "aventuras",
            ["sueno"] = "sueño",
            ["suenos"] = "sueños",
            ["pesadilla"] = "pesadilla",
            ["pesadillas"] = "pesadillas",
            ["fantasia"] = "fantasía",
            ["fantasias"] = "fantasías",
            ["realidad"] = "realidad",
            ["realidades"] = "realidades",
            ["oportunidad"] = "oportunidad",
            ["oportunidades"] = "oportunidades",
            ["posibilidad"] = "posibilidad",
            ["posibilidades"] = "posibilidades",
            ["calidad"] = "calidad",
            ["quantitad"] = "cantIDAD",

            // --- Palabras negativas ---
            ["no"] = "no",
            ["nada"] = "nada",
            ["nadie"] = "nadie",
            ["nunca"] = "nunca",
            ["jamás"] = "jamás",
            ["jamas"] = "jamás",
            ["tampoco"] = "tampoco",
            ["ni"] = "ni",
            ["pero"] = "pero",
            ["sino"] = "sino",
            ["sin"] = "sin",
            ["sin2"] = "sin",
            ["con"] = "con",
            ["para"] = "para",
            ["por"] = "por",
            ["entre"] = "entre",
            ["hacia"] = "hacia",
            ["sobre"] = "sobre",
            ["bajo2"] = "bajo",
            ["tras"] = "tras",
            ["ante"] = "ante",
            ["bajo3"] = "bajo",
            ["según"] = "según",
            ["segun"] = "según",

            // --- Pronombres / determinantes ---
            ["yo"] = "yo",
            ["nosotros"] = "nosotros",
            ["nosotras"] = "nosotras",
            ["usted"] = "usted",
            ["ustedes"] = "ustedes",
            ["ellos"] = "ellos",
            ["ellas"] = "ellas",
            ["nos"] = "nos",
            ["me"] = "me",
            ["le"] = "le",
            ["les"] = "les",
            ["lo"] = "lo",
            ["la"] = "la",
            ["los"] = "los",
            ["las"] = "las",
            ["este"] = "este",
            ["esta"] = "esta",
            ["esto"] = "esto",
            ["esta2"] = "esta",
            ["ese"] = "ese",
            ["esa"] = "esa",
            ["eso"] = "eso",
            ["aquel"] = "aquel",
            ["aquella"] = "aquella",
            ["aquellos"] = "aquellos",
            ["aquellas"] = "aquellas",
            ["algo"] = "algo",
            ["alguien"] = "alguien",
            ["algo2"] = "algo",

            // --- Adjetivos comunes ---
            ["bonito2"] = "bonito",
            ["bonita2"] = "bonita",
            ["hermoso"] = "hermoso",
            ["hermosa"] = "hermosa",
            ["lindo2"] = "lindo",
            ["linda2"] = "linda",
            ["feo2"] = "feo",
            ["fea2"] = "fea",
            ["bueno2"] = "bueno",
            ["buena2"] = "buena",
            ["malo2"] = "malo",
            ["mala2"] = "mala",
            ["grande2"] = "grande",
            ["pequeño2"] = "pequeño",
            ["pequeña2"] = "pequeña",
            ["nuevo2"] = "nuevo",
            ["nueva2"] = "nueva",
            ["viejo2b"] = "viejo",
            ["vieja2b"] = "vieja",
            ["largo"] = "largo",
            ["larga"] = "larga",
            ["corto"] = "corto",
            ["corta"] = "corta",
            ["alto"] = "alto",
            ["alta"] = "alta",
            ["bajo4"] = "bajo",
            ["baja"] = "baja",
            ["profundo"] = "profundo",
            ["profunda"] = "profunda",
            ["claro"] = "claro",
            ["clara"] = "clara",
            ["oscuro"] = "oscuro",
            ["oscura"] = "oscura",
            ["fuerte"] = "fuerte",
            ["fuertes"] = "fuertes",
            ["débil"] = "débil",
            ["debil"] = "débil",
            ["rapido"] = "rápido",
            ["rapida"] = "rápida",
            ["lento"] = "lento",
            ["lenta"] = "lenta",
            ["ultimo"] = "último",
            ["ultima"] = "última",
            ["primero"] = "primero",
            ["primera"] = "primera",
            ["unico"] = "único",
            ["unica"] = "única",
            ["raro"] = "raro",
            ["rara"] = "rara",
            ["igual"] = "igual",
            ["diferente"] = "diferente",
            ["distinto"] = "distinto",
            ["distinta"] = "distinta",
            ["mismo"] = "mismo",
            ["misma"] = "misma",
            ["otro"] = "otro",
            ["otra"] = "otra",
            ["otros"] = "otros",
            ["otras"] = "otras",
            ["todo"] = "todo",
            ["toda"] = "toda",
            ["todos"] = "todos",
            ["todas"] = "todas",
            ["mucho"] = "mucho",
            ["mucha"] = "mucha",
            ["muchos"] = "muchos",
            ["muchas"] = "muchas",
            ["poco"] = "poco",
            ["poca"] = "poca",
            ["pocos"] = "pocos",
            ["pocas"] = "pocas",
            ["cierto"] = "cierto",
            ["cierta"] = "cierta",
            ["falso"] = "falso",
            ["falsa"] = "falsa",
            ["verdadero"] = "verdadero",
            ["verdadera"] = "verdadera",
            ["posible"] = "posible",
            ["posibles"] = "posibles",
            ["imposible"] = "imposible",
            ["necesario"] = "necesario",
            ["necesaria"] = "necesaria",
            ["importante"] = "importante",
            ["importantes"] = "importantes",
            ["mejor"] = "mejor",
            ["peor"] = "peor",

            // --- Conjunciones y conectores ---
            ["y"] = "y",
            ["e"] = "e",
            ["u"] = "u",
            ["o"] = "o",
            ["ni2"] = "ni",
            ["que3"] = "que",
            ["como2"] = "como",
            ["porque"] = "porque",
            ["porqué"] = "porqué",
            ["por que"] = "por qué",
            ["aunque"] = "aunque",
            ["pero2"] = "pero",
            ["sino2"] = "sino",
            ["sino3"] = "sino",
            ["siempre2"] = "siempre",
            ["entonces"] = "entonces",
            ["ademas"] = "además",
            ["tambien"] = "también",
            ["tampoco2"] = "tampoco",

            // --- Tiempo verbal ---
            ["ahora"] = "ahora",
            ["antes2"] = "antes",
            ["despues2"] = "después",
            ["luego"] = "luego",
            ["pronto2"] = "pronto",
            ["temprano2"] = "temprano",
            ["tarde2"] = "tarde",
            ["anoche2"] = "anoche",
            ["hoy2"] = "hoy",
            ["ayer2"] = "ayer",
            ["manana2"] = "mañana",
            ["siempre3"] = "siempre",
            ["nunca2"] = "nunca",
            ["nunca3"] = "nunca",
            ["alguna vez"] = "alguna vez",
            ["otra vez"] = "otra vez",
            ["cada vez"] = "cada vez",
            ["a veces"] = "a veces",

            // --- Partes del cuerpo (en canciones) ---
            ["ojos"] = "ojos",
            ["boca"] = "boca",
            ["piel"] = "piel",
            ["cara"] = "cara",
            ["cabeza"] = "cabeza",
            ["manos2"] = "manos",
            ["brazos"] = "brazos",
            ["piernas"] = "piernas",
            ["corazon3"] = "corazón",
            ["alma2"] = "alma",
            ["almas2"] = "almas",

            // --- Colores ---
            ["rojo"] = "rojo",
            ["roja"] = "roja",
            ["azul"] = "azul",
            ["verde"] = "verde",
            ["blanco"] = "blanco",
            ["blanca"] = "blanca",
            ["negro"] = "negro",
            ["negra"] = "negra",
            ["amarillo"] = "amarillo",
            ["amarilla"] = "amarilla",
            ["gris"] = "gris",
            ["dorado"] = "dorado",
            ["dorada"] = "dorada",

            // --- Números con tilde ---
            ["dieciseis2"] = "dieciséis",
            ["veintidos2"] = "veintidós",
            ["veintitres2"] = "veintitrés",
            ["veintiseis2"] = "veintiséis",
        };

        /// <summary>
        /// Corrige la ortografía de un nombre de canción (sin extensión).
        /// Tokeniza por separadores, corrige cada palabra conocida y reensambla
        /// preservando los separadores y la capitalización original de cada palabra.
        /// Operación idempotente.
        /// </summary>
        public static string CorrectTitle(string nameWithoutExtension)
        {
            if (string.IsNullOrWhiteSpace(nameWithoutExtension))
                return nameWithoutExtension;

            var result = new StringBuilder(nameWithoutExtension.Length);
            int i = 0;
            while (i < nameWithoutExtension.Length)
            {
                // Si es separador (no letra), copiar tal cual
                if (!char.IsLetter(nameWithoutExtension[i]))
                {
                    result.Append(nameWithoutExtension[i]);
                    i++;
                    continue;
                }

                // Extraer palabra completa (letras)
                int start = i;
                while (i < nameWithoutExtension.Length && char.IsLetter(nameWithoutExtension[i]))
                    i++;

                var word = nameWithoutExtension[start..i];
                var corrected = CorrectWord(word);
                result.Append(corrected);
            }

            return result.ToString();
        }

        /// <summary>
        /// Corrige una sola palabra. Detecta la capitalización original (lower,
        /// UpperFirst, UPPER) y reaplica sobre la forma corregida.
        /// </summary>
        private static string CorrectWord(string word)
        {
            if (string.IsNullOrEmpty(word))
                return word;

            var lower = word.ToLowerInvariant();

            // Buscar en diccionario sin tilde
            if (!AccentedWords.TryGetValue(lower, out var correctedLower))
                return word; // Palabra desconocida: no se toca

            // Si la corrección es idéntica (ya correcta), devolver original
            if (string.Equals(lower, correctedLower, StringComparison.Ordinal))
                return word;

            // Reaplicar capitalización original
            return ApplyCapitalization(correctedLower, word);
        }

        /// <summary>
        /// Aplica el patrón de capitalización de <paramref name="original"/> sobre
        /// <paramref name="corrected"/>.
        /// </summary>
        private static string ApplyCapitalization(string corrected, string original)
        {
            if (string.IsNullOrEmpty(corrected))
                return corrected;

            // UPPER CASE original → UPPER CASE resultado
            if (original.Length > 1 && original == original.ToUpperInvariant())
                return corrected.ToUpperInvariant();

            // First letter uppercase → capitalize corrected
            if (char.IsUpper(original[0]))
            {
                return char.ToUpperInvariant(corrected[0]) + corrected[1..];
            }

            // Lowercase original → lowercase resultado
            return corrected.ToLowerInvariant();
        }
    }
}
